### ISSUE TITLE
Doesn't seem to be able to download definitions on macOS

### ISSUE THREAD

**Issue by andreiborisov** [cebby2420/via-desktop#4]
Getting this error in the console:

![CleanShot 2024-10-28 at 17 57 07@2x](https://github.com/user-attachments/assets/6b89df0c-a2c9-47e9-98c9-cc832bac8d46)

**Comment by cebby2420** [comment]
hey! which build are you using exactly? I've mostly tested on mac myself but maybe there's some difference in the environment.

It seems like the internal full webserver is failing to load anything, since the css file is also not loaded. Does the rest of the application do something or does the window stay white?

**Comment by cebby2420** [comment]
Found it, apparently the electron-settings module I used for the onlyLocalDefinitions setting doesn't work in the server process so it fails. And my testing probably never came in that case.

**Comment by cebby2420** [comment]
This should be fixed in the latest build.
